---
deployment:
  tasks:
  - export DEPLOYPATH=/home/example/public_html/
  - /bin/cp -rf main.py $DEPLOYPATH
  - /bin/cp -rf requirement.txt $DEPLOYPATH
  - /bin/cp -rf static $DEPLOYPATH
  - /bin/cp -rf templates $DEPLAYPATH
  - /bin/cp -rf venv $DEPLOYPATH
  - /bin/pip install -r requirements.txt
  - gunicorn main:app